[tox]
env_list =
    py311
    py312

minversion = 4.23.0

[testenv]
deps =
    cpanel-api>=0.3.0
    parsedatetime>=2.6

commands =
	{envpython} -m unittest discover -v -s test -p test_core.py
	{envpython} -m unittest discover -v -s test -p test_cli.py
	{envpython} -m unittest discover -v -s test -p test_dispatcher.py
setenv = PYTHONPATH=.

[testenv:integration]
commands = {envpython} -m unittest discover -v -s test -p test_uapi.py
